Repository Bnomad-space/IAteIt, pull requests merged in 2023-07, with the labels that each got.

#83 feat/다크모드 비활성화
  IAteIt/IAteIt.xcodeproj/project.pbxproj
  IAteIt/IAteIt/Info.plist
Labels: feature

#79 [Data] report 모델 및 함수 추가
  IAteIt/IAteIt.xcodeproj/project.pbxproj
  IAteIt/IAteIt/Model/Report.swift
  IAteIt/IAteIt/Network/FirebaseConnector+ExtensionForReports.swift
  IAteIt/IAteIt/View/MealDetail/Component/ReportView.swift
  IAteIt/IAteIt/View/MealDetail/MealDetailView.swift
Labels: feature

#82 [Feat] #77 MyProfileView meal history 데이터 연결 및 MealDetailView와 연결
  IAteIt/IAteIt.xcodeproj/project.pbxproj
  IAteIt/IAteIt/Model/Meal.swift
  IAteIt/IAteIt/Network/FirebaseConnector+ExtensionForMeals.swift
  IAteIt/IAteIt/Network/FirebaseTestView.swift
  IAteIt/IAteIt/Utility/CacheAsyncImage.swift
  IAteIt/IAteIt/Utility/Extension/View+Extension.swift
  IAteIt/IAteIt/Utility/InnerShadowModifier.swift
  IAteIt/IAteIt/View/Feed/Component/FeedHeaderView.swift
  IAteIt/IAteIt/View/Feed/Component/ProfilePhotoButtonView.swift
  IAteIt/IAteIt/View/Feed/FeedView.swift
  IAteIt/IAteIt/View/Feed/Model/FeedMealModel.swift
  IAteIt/IAteIt/View/MealDetail/Component/CommentView.swift
  IAteIt/IAteIt/View/MealDetail/Component/MealDetailTopView.swift
  IAteIt/IAteIt/View/MealDetail/Component/PhotoCardView.swift
  IAteIt/IAteIt/View/MealDetail/MealDetailView.swift
  IAteIt/IAteIt/View/MyProfile/Component/MealListRowView.swift
  IAteIt/IAteIt/View/MyProfile/Component/MealListView.swift
  IAteIt/IAteIt/View/MyProfile/Component/MealTileView.swift
  IAteIt/IAteIt/View/MyProfile/Component/PlateCountView.swift
  IAteIt/IAteIt/View/MyProfile/Component/PlateImageErrorView.swift
  IAteIt/IAteIt/View/MyProfile/Component/ProfileCellView.swift
  IAteIt/IAteIt/View/MyProfile/MyProfileView.swift
  IAteIt/IAteIt/View/Setting/Menu/EditProfileView.swift
Labels: feature

#87 [Bug] Unexpected NavigationPop by ForEach()
  IAteIt/IAteIt/View/Feed/FeedView.swift
  IAteIt/IAteIt/View/MealDetail/Component/AddCommentBarView.swift
  IAteIt/IAteIt/View/MealDetail/MealDetailView.swift
Labels: bug, PR Request

#88 [Enhancement] #84 Firestore database에 meal 저장하는 구조 변경
  IAteIt/IAteIt/Network/FirebaseConnector+ExtensionForMeals.swift
  IAteIt/IAteIt/Utility/Extension/DateFormatter.swift
  IAteIt/IAteIt/View/Feed/Model/FeedMealModel.swift
  IAteIt/IAteIt/View/Upload/CameraView.swift
Labels: enhancement

#93 [Hotfix] EditProfileView에서도 username 알파벳 소문자 적용
  IAteIt/IAteIt/View/Setting/Menu/EditProfileView.swift
Labels: hotfix

#95 [Feat] #94 meal 삭제 시 comment도 있으면 삭제
  IAteIt/IAteIt/View/Feed/Model/FeedMealModel.swift
  IAteIt/IAteIt/View/Upload/CameraView.swift
Labels: feature

#97 [Enhancement] #96 코멘트 작성시간 수정 외
  IAteIt/IAteIt/View/MealDetail/Component/CommentView.swift
  IAteIt/IAteIt/View/MealDetail/Component/PhotoCardView.swift
  IAteIt/IAteIt/View/MealDetail/MealDetailView.swift
Labels: enhancement

#92 [Feat] reportView UI 수정
  IAteIt/IAteIt/View/MealDetail/Component/ReportView.swift
  IAteIt/IAteIt/View/MealDetail/MealDetailView.swift
Labels: feature

#98 [hotfix] CameraView에서 시간 캡슐 보이는 것 삭제
  IAteIt/IAteIt/View/Upload/CameraView.swift
Labels: hotfix

#100 [Feat] #99 앱 아이콘, 런치스크린 추가 등
  IAteIt/IAteIt.xcodeproj/project.pbxproj
  IAteIt/IAteIt/Application/Assets.xcassets/AppIcon.appiconset/AppIcon_42.png
  IAteIt/IAteIt/Application/Assets.xcassets/AppIcon.appiconset/Contents.json
  IAteIt/IAteIt/Application/Assets.xcassets/AppIcon_42.imageset/AppIcon_42.png
  IAteIt/IAteIt/Application/Assets.xcassets/AppIcon_42.imageset/Contents.json
  IAteIt/IAteIt/Application/Assets.xcassets/AppLogo80x80.imageset/AppLogo80x80.png
  IAteIt/IAteIt/Application/Assets.xcassets/AppLogo80x80.imageset/Contents.json
  IAteIt/IAteIt/Application/Assets.xcassets/Sample_Coffee.imageset/Contents.json
  IAteIt/IAteIt/Application/Assets.xcassets/Sample_Coffee.imageset/Sample_Coffee.jpg
  IAteIt/IAteIt/Application/Assets.xcassets/Sample_Hashbrown.imageset/Sample_Hashbrown.jpg
  IAteIt/IAteIt/Application/Assets.xcassets/Sample_McMorning.imageset/Contents.json
  IAteIt/IAteIt/Application/Assets.xcassets/Sample_McMorning.imageset/Sample_McMorning.jpg
  IAteIt/IAteIt/Application/Assets.xcassets/Sample_Profile1.imageset/Contents.json
  IAteIt/IAteIt/Application/Assets.xcassets/Sample_Profile1.imageset/Sample_Profile1.jpg
  IAteIt/IAteIt/Application/Assets.xcassets/Sample_Profile2.imageset/Sample_Profile2.jpg
  IAteIt/IAteIt/Application/Assets.xcassets/Sample_Profile3.imageset/Contents.json
  IAteIt/IAteIt/Application/Assets.xcassets/Sample_Profile3.imageset/Sample_Profile3.jpg
  IAteIt/IAteIt/Application/Assets.xcassets/white.colorset/Contents.json
  IAteIt/IAteIt/Application/LaunchScreen.storyboard
  IAteIt/IAteIt/Model/TempComment.swift
  IAteIt/IAteIt/Model/TempFeedHeader.swift
  IAteIt/IAteIt/Model/TempModel.swift
  IAteIt/IAteIt/Model/TempPlate.swift
  IAteIt/IAteIt/Network/FirebaseTestView.swift
  IAteIt/IAteIt/View/Feed/Component/FeedTitleView.swift
  IAteIt/IAteIt/View/Feed/FeedView.swift
  IAteIt/IAteIt/View/MealDetail/MealDetailView.swift
Labels: feature
