Repository Bnomad-space/IAteIt, pull requests merged in 2023-06, with the labels that each got.

#68 [Feat] DetailView comment 바운딩박스, 흰배경 추가
  IAteIt/IAteIt/View/MealDetail/MealDetailView.swift
Labels: feature

#74 [Feat] 코멘트 삭제기능 구현
  IAteIt/IAteIt/Network/FirebaseConnector+ExtensionForComments.swift
  IAteIt/IAteIt/View/Feed/Model/FeedMealModel.swift
  IAteIt/IAteIt/View/MealDetail/MealDetailView.swift
  IAteIt/IAteIt/View/SignUp/Model/LoginStateModel.swift
Labels: enhancement, feature

#67 [Feat] #65 Delete Account 기능
  IAteIt/IAteIt.xcodeproj/project.pbxproj
  IAteIt/IAteIt/Application/IAteItApp.swift
  IAteIt/IAteIt/Network/FirebaseConnector+ExtensionForComments.swift
  IAteIt/IAteIt/Network/FirebaseConnector+ExtensionForMeals.swift
  IAteIt/IAteIt/Network/FirebaseConnector.swift
  IAteIt/IAteIt/Utility/Extension/EnvironmentValues+Extension.swift
  IAteIt/IAteIt/View/Feed/Component/FeedHeaderView.swift
  IAteIt/IAteIt/View/Feed/FeedView.swift
  IAteIt/IAteIt/View/MyProfile/MyProfileView.swift
  IAteIt/IAteIt/View/Setting/SettingView.swift
  IAteIt/IAteIt/View/SignUp/LoginView.swift
  IAteIt/IAteIt/View/SignUp/Model/LoginStateModel.swift
  IAteIt/IAteIt/View/SignUp/SignUpSecondView.swift
  IAteIt/IAteIt/View/SignUp/SignUpView.swift
Labels: feature, PR Request
