Repository Bnomad-space/IAteIt, pull requests merged in 2023-05, with the labels that each got.

#32 [Feat] ProfileViewUpdate
  IAteIt/IAteIt.xcodeproj/project.pbxproj
  IAteIt/IAteIt.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  IAteIt/IAteIt/Model/Meal.swift
  IAteIt/IAteIt/Model/Plate.swift
  IAteIt/IAteIt/View/MyProfile/Component/MealListRowView.swift
  IAteIt/IAteIt/View/MyProfile/Component/MealListView.swift
  IAteIt/IAteIt/View/MyProfile/Component/ProfileCellView.swift
  IAteIt/IAteIt/View/MyProfile/DailyMealCellView.swift
  IAteIt/IAteIt/View/MyProfile/MyProfileView.swift
Labels: feature

#39 [Feat] #38 애플로그인, Firebase 회원가입 연동
  IAteIt/IAteIt.xcodeproj/project.pbxproj
  IAteIt/IAteIt/Application/IAteItApp.swift
  IAteIt/IAteIt/Network/FirebaseConnector.swift
  IAteIt/IAteIt/View/Feed/Component/FeedHeaderView.swift
  IAteIt/IAteIt/View/Feed/FeedView.swift
  IAteIt/IAteIt/View/SignUp/LoginView.swift
  IAteIt/IAteIt/View/SignUp/Model/LoginStateModel.swift
  IAteIt/IAteIt/View/SignUp/SignUpSecondView.swift
  IAteIt/IAteIt/View/SignUp/SignUpView.swift
Labels: feature

#41 [Feat] 피드뷰 간단한 데이터정리
  IAteIt/IAteIt/View/Feed/FeedView.swift
Labels: feature

#47 [Hotfix] FeedView - index out of range 에러
  IAteIt/IAteIt/View/Feed/Component/FeedHeaderView.swift
  IAteIt/IAteIt/View/Feed/FeedView.swift
Labels: hotfix

#48 [Feat] Comment 연결
  IAteIt/IAteIt/Network/FirebaseConnector+ExtensionForComments.swift
  IAteIt/IAteIt/Network/FirebaseConnector.swift
  IAteIt/IAteIt/Network/FirebaseTestView.swift
  IAteIt/IAteIt/View/Feed/Component/FeedFooterView.swift
  IAteIt/IAteIt/View/Feed/Component/FeedHeaderView.swift
  IAteIt/IAteIt/View/Feed/FeedView.swift
  IAteIt/IAteIt/View/Feed/Model/FeedMealModel.swift
  IAteIt/IAteIt/View/MealDetail/Component/AddCommentBarView.swift
  IAteIt/IAteIt/View/MealDetail/Component/CommentView.swift
  IAteIt/IAteIt/View/MealDetail/MealDetailView.swift
Labels: PR Request

#49 emptyMealVIew 추가 (피드뷰 초기화면)
  IAteIt/IAteIt.xcodeproj/project.pbxproj
  IAteIt/IAteIt/View/Feed/Component/EmptyMealView.swift
  IAteIt/IAteIt/View/Feed/FeedView.swift
Labels: feature

#54 [Fix] 불필요 fetch 줄임
  IAteIt/IAteIt/View/Feed/FeedView.swift
  IAteIt/IAteIt/View/Feed/Model/FeedMealModel.swift
Labels: PR Request

#51 [Feat] #50 SettingView, EditProfileView UI 작업
  IAteIt/IAteIt.xcodeproj/project.pbxproj
  IAteIt/IAteIt/Application/IAteItApp.swift
  IAteIt/IAteIt/View/Feed/FeedView.swift
  IAteIt/IAteIt/View/MyProfile/MyProfileView.swift
  IAteIt/IAteIt/View/Setting/Component/SettingListTitleView.swift
  IAteIt/IAteIt/View/Setting/Menu/EditProfileView.swift
  IAteIt/IAteIt/View/Setting/SettingView.swift
Labels: PR Request

#56 [Feat] #55 UploadView 카메라 관련 오류 수정
  IAteIt/IAteIt/View/Upload/Camera.swift
  IAteIt/IAteIt/View/Upload/CameraView.swift
  IAteIt/IAteIt/View/Upload/CameraViewModel.swift
Labels: feature

#53 [Feat] #44 Meal에 Plate 추가, 캡션/장소 저장
  IAteIt/IAteIt.xcodeproj/project.pbxproj
  IAteIt/IAteIt/Application/IAteItApp.swift
  IAteIt/IAteIt/Network/FirebaseConnector+ExtensionForMeals.swift
  IAteIt/IAteIt/Network/FirebaseTestView.swift
  IAteIt/IAteIt/View/Feed/Component/FeedHeaderView.swift
  IAteIt/IAteIt/View/Feed/FeedView.swift
  IAteIt/IAteIt/View/Feed/Model/FeedMealModel.swift
  IAteIt/IAteIt/View/MealDetail/Component/AddCommentBarView.swift
  IAteIt/IAteIt/View/MealDetail/Component/AddPlateButtonView.swift
  IAteIt/IAteIt/View/MealDetail/Component/MealDetailTopView.swift
  IAteIt/IAteIt/View/MealDetail/MealDetailView.swift
  IAteIt/IAteIt/View/Upload/CameraView.swift
  IAteIt/IAteIt/View/Upload/CameraViewModel.swift
Labels: PR Request

#59 [feat] 캡쳐버튼 관련 오류 수정
  IAteIt/IAteIt/View/Feed/FeedView.swift
  IAteIt/IAteIt/View/MealDetail/MealDetailView.swift
  IAteIt/IAteIt/View/Upload/CameraView.swift
  IAteIt/IAteIt/View/Upload/CameraViewModel.swift
Labels: feature

#60 [Feat] meal, comment 순서대로 작동으로 수정
  IAteIt/IAteIt/View/Feed/Model/FeedMealModel.swift
Labels: PR Request

#62 [fix] meal order 수정
  IAteIt/IAteIt/View/Feed/Model/FeedMealModel.swift
Labels: PR Request

#61 [Feat] #58 meal, plate 삭제 기능
  IAteIt/IAteIt/Network/FirebaseConnector+ExtensionForMeals.swift
  IAteIt/IAteIt/View/Feed/Model/FeedMealModel.swift
  IAteIt/IAteIt/View/MealDetail/MealDetailView.swift
  IAteIt/IAteIt/View/Upload/CameraView.swift
Labels: feature

#63 [Feat] comment의 meal 의존성 삭제 + 뒤로가는 버그 수정
  IAteIt/IAteIt/View/Feed/Component/FeedFooterView.swift
  IAteIt/IAteIt/View/Feed/FeedView.swift
  IAteIt/IAteIt/View/Feed/Model/FeedMealModel.swift
  IAteIt/IAteIt/View/MealDetail/MealDetailView.swift
Labels: PR Request

#65 [Feat] #64 프로필 수정 기능
  IAteIt/IAteIt.xcodeproj/project.pbxproj
  IAteIt/IAteIt/Network/FirebaseConnector.swift
  IAteIt/IAteIt/Network/FirebaseTestView.swift
  IAteIt/IAteIt/Utility/Extension/Image+Extension.swift
  IAteIt/IAteIt/View/Feed/FeedView.swift
  IAteIt/IAteIt/View/MyProfile/MyProfileView.swift
  IAteIt/IAteIt/View/Setting/Menu/EditProfileView.swift
  IAteIt/IAteIt/View/Setting/SettingView.swift
  IAteIt/IAteIt/View/SignUp/SignUpSecondView.swift
Labels: PR Request
