Repository Bnomad-space/IAteIt, pull requests merged in 2023-09, with the labels that each got.

#105 [Feat] #101 Setting 메뉴 추가, Blocked Users 메뉴 기능 구현
  IAteIt/IAteIt.xcodeproj/project.pbxproj
  IAteIt/IAteIt/Model/User.swift
  IAteIt/IAteIt/Network/FirebaseConnector.swift
  IAteIt/IAteIt/View/Setting/Component/BlockedUserView.swift
  IAteIt/IAteIt/View/Setting/Menu/BlockedUsersView.swift
  IAteIt/IAteIt/View/Setting/SettingView.swift
  IAteIt/IAteIt/View/SignUp/Model/LoginStateModel.swift
Labels: feature

#106 [enhancement] KingFisher 도입
  IAteIt/IAteIt.xcodeproj/project.pbxproj
  IAteIt/IAteIt.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  IAteIt/IAteIt/Utility/CacheAsyncImage.swift
  IAteIt/IAteIt/Utility/Extension/Image+Extension.swift
  IAteIt/IAteIt/View/Feed/Component/FeedHeaderView.swift
  IAteIt/IAteIt/View/Feed/Component/ProfileImageDefaultView.swift
  IAteIt/IAteIt/View/Feed/Component/ProfileImageErrorView.swift
  IAteIt/IAteIt/View/Feed/Component/ProfilePhotoButtonView.swift
  IAteIt/IAteIt/View/MealDetail/Component/CommentView.swift
  IAteIt/IAteIt/View/MealDetail/Component/PhotoCardView.swift
  IAteIt/IAteIt/View/MealDetail/Component/ReportView.swift
  IAteIt/IAteIt/View/MyProfile/Component/MealTileView.swift
  IAteIt/IAteIt/View/MyProfile/Component/PlateImageErrorView.swift
  IAteIt/IAteIt/View/MyProfile/Component/ProfileCellView.swift
  IAteIt/IAteIt/View/Setting/Menu/EditProfileView.swift
Labels: enhancement

#107 [hotfix] BlockedUserView 프로필 이미지 수정
  IAteIt/IAteIt/View/Setting/Component/BlockedUserView.swift
Labels: hotfix

#109 [feat] #108 terms of use, privacy policy 추가
  IAteIt/IAteIt.xcodeproj/project.pbxproj
  IAteIt/IAteIt/Utility/Constants.swift
  IAteIt/IAteIt/Utility/WebView.swift
  IAteIt/IAteIt/View/Setting/SettingView.swift
  IAteIt/IAteIt/View/SignUp/SignUpSecondView.swift
Labels: feature

#111 [Bug] BlockedId 필드 없으면 Feed 안보이는 문제 해결, Firestore 보안 규칙 작성
  IAteIt/IAteIt/Network/FirebaseConnector+ExtensionForMeals.swift
  IAteIt/IAteIt/View/Feed/FeedView.swift
  IAteIt/IAteIt/View/MealDetail/MealDetailView.swift
  IAteIt/IAteIt/View/SignUp/Model/LoginStateModel.swift
Labels: bug

#114 [feat] meal PinchZoom 액션 추가
  IAteIt/IAteIt/Utility/Extension/View+Extension.swift
  IAteIt/IAteIt/View/Feed/FeedView.swift
  IAteIt/IAteIt/View/MealDetail/MealDetailView.swift
Labels: feature, PR Request

#117 [bug] 자신의 코멘트 오른쪽 버튼 탭 어려움 해결
  IAteIt/IAteIt/Utility/Constants.swift
  IAteIt/IAteIt/View/MealDetail/MealDetailView.swift
Labels: bug

#119 [fix] 차단당한 유저가 차단한 유저의 게시물을 볼 수 없도록 함
  IAteIt/IAteIt/View/Feed/FeedView.swift
  IAteIt/IAteIt/View/Feed/Model/FeedMealModel.swift
  IAteIt/IAteIt/View/SignUp/Model/LoginStateModel.swift
Labels: enhancement

#121 [fix] pinchzoom 버그 수정
  IAteIt/IAteIt/Utility/Constants.swift
  IAteIt/IAteIt/Utility/Extension/View+Extension.swift
  IAteIt/IAteIt/View/Feed/Component/AddMealView.swift
  IAteIt/IAteIt/View/Feed/FeedView.swift
  IAteIt/IAteIt/View/MealDetail/Component/PhotoCardView.swift
  IAteIt/IAteIt/View/MealDetail/Component/ReportView.swift
  IAteIt/IAteIt/View/MealDetail/MealDetailView.swift
Labels: bug
