Repository Bnomad-space/IAteIt, pull requests merged in 2024-06, with the labels that each got.

#138 [Enhancement] #131 Meal, Comment 관련 비동기 구문 정리
  IAteIt/IAteIt/Network/FirebaseConnector+ExtensionForComments.swift
  IAteIt/IAteIt/View/MealDetail/MealDetailView.swift
  IAteIt/IAteIt/ViewModel/FeedMealStore.swift
Labels: enhancement

#141 [수정] 프로필뷰 변경사항 적용 & 스크립트 항상 run~
  IAteIt/IAteIt.xcodeproj/project.pbxproj
  IAteIt/IAteIt/View/MealDetail/Component/AddCommentBarView.swift
  IAteIt/IAteIt/View/MealDetail/Component/MealDetailTopView.swift
  IAteIt/IAteIt/View/MealDetail/MealDetailView.swift
  IAteIt/IAteIt/View/MyProfile/Component/MealListView.swift
  IAteIt/IAteIt/View/MyProfile/MyProfileView.swift
  IAteIt/IAteIt/ViewModel/FeedMealStore.swift
Labels: bug, enhancement

#142 [Feat] #140 로컬 알림 추가
  IAteIt/IAteIt.xcodeproj/project.pbxproj
  IAteIt/IAteIt/Application/AppDelegate.swift
  IAteIt/IAteIt/Model/LocalNotification.swift
  IAteIt/IAteIt/Utility/Extension/UNUserNotificationCenter+Extension.swift
Labels: feature

#143 [Docs] README 업데이트
  README.md
Labels: documentation
