Repository Bnomad-space/IAteIt, pull requests merged in 2024-05, with the labels that each got.

#126 불필요 파일 삭제 및 회원가입 로직 모델로 분리
  IAteIt/IAteIt.xcodeproj/project.pbxproj
  IAteIt/IAteIt/Model/User.swift
  IAteIt/IAteIt/Network/FirebaseConnector+ExtensionForComments.swift
  IAteIt/IAteIt/Network/FirebaseConnector+ExtensionForMeals.swift
  IAteIt/IAteIt/Network/FirebaseConnector.swift
  IAteIt/IAteIt/View/Feed/Model/FeedMealModel.swift
  IAteIt/IAteIt/View/SignUp/Model/UsernameValidModel.swift
  IAteIt/IAteIt/View/SignUp/SignUpSecondView.swift
  IAteIt/IAteIt/View/SignUp/SignUpView.swift
Labels: enhancement

#127 [수정] 빌드 중복 제거
  IAteIt/IAteIt.xcodeproj/project.pbxproj
Labels: enhancement

#133 [Feat] #130 Firebase Analytics, Crashlytics 추가
  IAteIt/IAteIt.xcodeproj/project.pbxproj
  IAteIt/IAteIt.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: feature

#134 [추가 리팩] 로그아웃, LoginState 관련 리팩토링
  IAteIt/IAteIt/View/Feed/FeedView.swift
  IAteIt/IAteIt/View/MealDetail/Component/PhotoCardView.swift
  IAteIt/IAteIt/View/Setting/SettingView.swift
  IAteIt/IAteIt/View/SignUp/LoginView.swift
  IAteIt/IAteIt/View/SignUp/SignUpSecondView.swift
  IAteIt/IAteIt/View/SignUp/SignUpView.swift
  IAteIt/IAteIt/ViewModel/LoginStateStore.swift
Labels: enhancement, feature

#136 [추가] privacy manifest 추가
  IAteIt/IAteIt.xcodeproj/project.pbxproj
  IAteIt/IAteIt/Application/PrivacyInfo.xcprivacy
Labels: feature

#137 [수정] MyMealHistory 진입시 댓글 fetch 안하게 변경
  IAteIt/IAteIt/View/Feed/FeedView.swift
  IAteIt/IAteIt/View/MealDetail/MealDetailView.swift
  IAteIt/IAteIt/View/MyProfile/Component/MealListView.swift
  IAteIt/IAteIt/View/MyProfile/MyProfileView.swift
  IAteIt/IAteIt/ViewModel/FeedMealStore.swift
Labels: enhancement
